// app/tools/cost-calculator/page.tsx
'use client';

import { useState, useCallback } from 'react';

interface CostResult {
    totalCost: number;
    unitCost: number;
    margin: number;
    breakeven: number;
}

export default function CostCalculatorPage() {
    const [materialCost, setMaterialCost] = useState(1000);
    const [laborCost, setLaborCost] = useState(500);
    const [overheadCost, setOverheadCost] = useState(200);
    const [quantity, setQuantity] = useState(10);
    const [sellingPrice, setSellingPrice] = useState(250);
    const [result, setResult] = useState<CostResult | null>(null);

    const handleCalculate = useCallback(() => {
        const totalCost = materialCost + laborCost + overheadCost;
        const unitCost = quantity > 0 ? totalCost / quantity : 0;
        const margin = sellingPrice > 0 ? ((sellingPrice - unitCost) / sellingPrice) * 100 : 0;
        const breakeven = unitCost > 0 && sellingPrice > unitCost
            ? Math.ceil(totalCost / (sellingPrice - unitCost))
            : 0;

        setResult({
            totalCost: Math.round(totalCost),
            unitCost: Math.round(unitCost * 100) / 100,
            margin: Math.round(margin * 10) / 10,
            breakeven,
        });
    }, [materialCost, laborCost, overheadCost, quantity, sellingPrice]);

    return (
        <div className="container max-w-4xl mx-auto px-4 py-12">
            <div className="glass-panel rounded-3xl p-8">
                {/* H1 + 用途說明 */}
                <h1 className="text-3xl font-bold text-slate-900 mb-3">成本計算器</h1>
                <p className="text-slate-600 mb-8 text-lg">
                    快速計算產品或服務的實際成本，避免報價錯誤或低估支出，讓每一筆生意都算得清楚。
                </p>

                {/* 使用情境 */}
                <div className="glass-card rounded-2xl p-5 mb-8">
                    <h2 className="text-sm font-semibold text-slate-500 mb-3">📌 使用情境</h2>
                    <ul className="text-slate-600 space-y-2 text-sm">
                        <li>• 接案前確認是否會虧錢</li>
                        <li>• 商品定價前估算成本結構</li>
                        <li>• 比較不同方案的成本差異</li>
                    </ul>
                </div>

                {/* 計算器 UI */}
                <div className="grid gap-6 md:grid-cols-2 mb-8">
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            材料成本 (NT$)
                        </label>
                        <input
                            type="number"
                            value={materialCost}
                            onChange={(e) => setMaterialCost(Number(e.target.value))}
                            className="glass-input w-full px-4 py-3 rounded-xl text-lg"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            人工成本 (NT$)
                        </label>
                        <input
                            type="number"
                            value={laborCost}
                            onChange={(e) => setLaborCost(Number(e.target.value))}
                            className="glass-input w-full px-4 py-3 rounded-xl text-lg"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            其他費用 (NT$)
                        </label>
                        <input
                            type="number"
                            value={overheadCost}
                            onChange={(e) => setOverheadCost(Number(e.target.value))}
                            className="glass-input w-full px-4 py-3 rounded-xl text-lg"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            預計數量
                        </label>
                        <input
                            type="number"
                            value={quantity}
                            onChange={(e) => setQuantity(Number(e.target.value))}
                            className="glass-input w-full px-4 py-3 rounded-xl text-lg"
                        />
                    </div>
                    <div className="md:col-span-2">
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            預計售價 (NT$)
                        </label>
                        <input
                            type="number"
                            value={sellingPrice}
                            onChange={(e) => setSellingPrice(Number(e.target.value))}
                            className="glass-input w-full px-4 py-3 rounded-xl text-lg"
                        />
                    </div>
                </div>

                <button
                    onClick={handleCalculate}
                    className="btn-primary w-full py-4 rounded-xl text-lg font-semibold"
                >
                    計算成本
                </button>

                {/* 結果區 */}
                {result && (
                    <div className="mt-8 space-y-6">
                        <div className="grid gap-4 md:grid-cols-2">
                            <div className="glass-card rounded-2xl p-6 text-center">
                                <p className="text-slate-500 mb-2">總成本</p>
                                <p className="text-3xl font-bold font-mono text-slate-800">
                                    NT$ {result.totalCost.toLocaleString()}
                                </p>
                            </div>
                            <div className="glass-card rounded-2xl p-6 text-center">
                                <p className="text-slate-500 mb-2">單位成本</p>
                                <p className="text-3xl font-bold font-mono text-gradient-primary">
                                    NT$ {result.unitCost.toLocaleString()}
                                </p>
                            </div>
                            <div className="glass-card rounded-2xl p-6 text-center">
                                <p className="text-slate-500 mb-2">毛利率</p>
                                <p className={`text-3xl font-bold font-mono ${result.margin >= 0 ? 'text-green-600' : 'text-red-500'}`}>
                                    {result.margin}%
                                </p>
                            </div>
                            <div className="glass-card rounded-2xl p-6 text-center">
                                <p className="text-slate-500 mb-2">損益兩平數量</p>
                                <p className="text-3xl font-bold font-mono text-indigo-600">
                                    {result.breakeven > 0 ? `${result.breakeven} 件` : '—'}
                                </p>
                            </div>
                        </div>

                        {/* 簡單解釋 */}
                        <div className="glass-surface rounded-xl p-4 text-center text-slate-600">
                            {result.margin >= 20
                                ? '✅ 利潤空間健康，可考慮執行'
                                : result.margin >= 0
                                    ? '⚠️ 利潤偏低，建議重新評估定價或成本'
                                    : '❌ 目前定價會虧損，請調整'}
                        </div>
                    </div>
                )}

                {/* 小提醒 */}
                <div className="mt-8 text-sm text-slate-400 text-center">
                    💡 結果僅供參考，實際請依情況調整
                </div>

                {/* FAQ */}
                <div className="mt-10 border-t border-slate-200 pt-8">
                    <h2 className="text-lg font-semibold text-slate-800 mb-4">常見問題</h2>
                    <div className="space-y-4">
                        <div>
                            <h3 className="font-medium text-slate-700">Q：計算結果準確嗎？</h3>
                            <p className="text-slate-500 text-sm mt-1">
                                只要輸入正確數據，結果即時且精準。建議多嘗試不同情境來比較。
                            </p>
                        </div>
                        <div>
                            <h3 className="font-medium text-slate-700">Q：其他費用應該包含什麼？</h3>
                            <p className="text-slate-500 text-sm mt-1">
                                可包含運費、包材、水電、租金分攤等間接成本。
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/components/calculators/CostCalculator.vue
<template>
  <div class="space-y-6">
    <!-- 輸入區 -->
    <div class="card rounded-2xl p-6 md:p-8 space-y-6">
      <div class="grid grid-cols-2 gap-4">
        <div>
          <label for="material" class="block text-xs font-semibold text-stone-500 mb-2">材料成本</label>
          <div class="relative">
            <input
              id="material"
              type="number"
              v-model.number="material"
              class="w-full bg-stone-50 border border-stone-200 rounded-xl py-2.5 px-3 text-stone-800 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
            />
          </div>
        </div>
        <div>
          <label for="labor" class="block text-xs font-semibold text-stone-500 mb-2">人工成本</label>
          <div class="relative">
            <input
              id="labor"
              type="number"
              v-model.number="labor"
              class="w-full bg-stone-50 border border-stone-200 rounded-xl py-2.5 px-3 text-stone-800 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
            />
          </div>
        </div>
      </div>

      <div class="grid grid-cols-2 gap-4">
        <div>
          <label for="overhead" class="block text-xs font-semibold text-stone-500 mb-2">其他費用</label>
          <div class="relative">
            <input
              id="overhead"
              type="number"
              v-model.number="overhead"
              class="w-full bg-stone-50 border border-stone-200 rounded-xl py-2.5 px-3 text-stone-800 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
            />
          </div>
        </div>
        <div>
          <label for="quantity" class="block text-xs font-semibold text-stone-500 mb-2">預計數量</label>
          <input
            id="quantity"
            type="number"
            v-model.number="quantity"
            min="1"
            class="w-full bg-stone-50 border border-stone-200 rounded-xl py-2.5 px-3 text-stone-800 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
          />
        </div>
      </div>

      <div>
        <label for="price" class="block text-xs font-semibold text-stone-500 mb-2 uppercase tracking-wide">
          預計售價
        </label>
        <div class="relative">
          <input
            id="price"
            type="number"
            v-model.number="price"
            class="w-full bg-stone-50 border border-stone-200 rounded-xl py-3 px-4 text-stone-800 text-xl font-bold focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
          />
        </div>
      </div>
    </div>

    <!-- 結果區 -->
    <div class="grid grid-cols-2 gap-4">
      <div class="bg-stone-50 rounded-xl p-4 border border-stone-200 text-center">
        <p class="text-xs text-stone-500 mb-1">總成本</p>
        <p class="text-xl font-bold font-mono text-stone-700">${{ fmt(totalCost) }}</p>
      </div>
      <div class="bg-emerald-50 rounded-xl p-4 border border-emerald-100 text-center">
        <p class="text-xs text-emerald-600 mb-1">單位成本</p>
        <p class="text-xl font-bold font-mono text-emerald-600">${{ fmt(unitCost) }}</p>
      </div>
      <div class="bg-stone-50 rounded-xl p-4 border border-stone-200 text-center">
        <p class="text-xs text-stone-500 mb-1">毛利率</p>
        <p class="text-xl font-bold font-mono" :class="margin >= 0 ? 'text-emerald-600' : 'text-rose-500'">
          {{ margin.toFixed(1) }}%
        </p>
      </div>
      <div class="bg-stone-50 rounded-xl p-4 border border-stone-200 text-center">
        <p class="text-xs text-stone-500 mb-1">損益兩平</p>
        <p class="text-xl font-bold font-mono text-blue-600">
          {{ breakeven > 0 ? breakeven + ' 件' : '—' }}
        </p>
      </div>
    </div>

    <!-- 判斷提示 -->
    <div class="text-sm text-center py-3 rounded-lg border" :class="verdictClass">
      {{ verdict }}
    </div>

    <!-- 複製按鈕 -->
    <button
      @click="copyResult"
      class="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3.5 rounded-xl transition-all active:scale-[0.98] flex items-center justify-center gap-2 shadow-lg shadow-emerald-600/20"
    >
      <svg
        v-if="!copied"
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
        <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
      </svg>
      <svg
        v-else
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="3"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <polyline points="20 6 9 17 4 12"></polyline>
      </svg>
      {{ copied ? '已複製結果！' : '複製結果' }}
    </button>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';

const material = ref(1000);
const labor = ref(500);
const overhead = ref(200);
const quantity = ref(10);
const price = ref(250);
const copied = ref(false);

const fmt = (n) => n.toLocaleString('zh-TW');

const totalCost = computed(() => (material.value || 0) + (labor.value || 0) + (overhead.value || 0));

const unitCost = computed(() => {
  const q = quantity.value || 1;
  return Math.round((totalCost.value / q) * 100) / 100;
});

const margin = computed(() => {
  const p = price.value || 0;
  if (p <= 0) return 0;
  return ((p - unitCost.value) / p) * 100;
});

const breakeven = computed(() => {
  const p = price.value || 0;
  if (unitCost.value <= 0 || p <= unitCost.value) return 0;
  return Math.ceil(totalCost.value / (p - unitCost.value));
});

const verdict = computed(() => {
  if (margin.value >= 20) return '✅ 利潤空間健康，可考慮執行';
  if (margin.value >= 0) return '⚠️ 利潤偏低，建議重新評估定價或成本';
  return '❌ 目前定價會虧損，請調整';
});

const verdictClass = computed(() => {
  if (margin.value >= 20) return 'bg-emerald-50 text-emerald-700 border-emerald-200';
  if (margin.value >= 0) return 'bg-amber-50 text-amber-700 border-amber-200';
  return 'bg-rose-50 text-rose-700 border-rose-200';
});

const copyResult = async () => {
  const text = `成本分析：總成本 $${fmt(totalCost.value)}，單位成本 $${fmt(unitCost.value)}，毛利率 ${margin.value.toFixed(
    1
  )}%，損益兩平 ${breakeven.value} 件`;
  try {
    await navigator.clipboard.writeText(text);
    copied.value = true;
    setTimeout(() => (copied.value = false), 1500);
  } catch (e) {
    alert('Copy failed');
  }
};
</script>
